AWSTemplateFormatVersion: 2010-09-09
Description: Subnets.
Parameters:
  NetworkStackNameParameter:
    Type: String
Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP ingress
      VpcId: !ImportValue 
        'Fn::Sub': '${NetworkStackNameParameter}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: WebSecurityGroup
Outputs:
  WebServerSecurityGroup:
    Description: The subnet ID to use for public web servers
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-WebServerSecurityGroup'
